### ISSUE TITLE
Need tkontrak_penunjukan schema and sample data

### ISSUE THREAD

**Issue by mireille-raad** [OC-Bandung/OCDS-publication#2]
In the query there is a join on the pgid 

`2016_birms_econtract.tkontrak_penunjukan ON tpengadaan.pgid = tkontrak_penunjukan.pgid`

The fields are used for contract start date and contract end date.

The database name for this table is: birms_econtract

@bdgcoder , can you add to the private dropbox the schema and data?

**Comment by bdgcoder** [comment]
I am currently not open your email last weekend. Check your drop box please.
